version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: clean-css
    versions:
    - 4.2.3
